# Generated by Django 4.1.3 on 2022-12-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated',
        ),
        migrations.AddField(
            model_name='post',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='post',
            name='coordinates_x',
            field=models.PositiveSmallIntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='post',
            name='coordinates_y',
            field=models.PositiveSmallIntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='post',
            name='height',
            field=models.PositiveSmallIntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='post',
            name='number',
            field=models.PositiveSmallIntegerField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='post',
            name='table_form',
            field=models.CharField(choices=[('elips', 'ELIPS'), ('square', 'SQUARE')], default='square', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='width',
            field=models.PositiveSmallIntegerField(default=0, max_length=1),
        ),
    ]
