# Generated by Django 4.1.3 on 2022-12-05 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_remove_post_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='table',
        ),
    ]
