# Generated by Django 4.1.3 on 2022-12-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0007_remove_table_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('data', models.CharField(max_length=255)),
                ('tableitem', models.CharField(max_length=255)),
            ],
        ),
    ]
