# Generated by Django 4.1.3 on 2022-12-06 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0008_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='data',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
