# Generated by Django 4.1.3 on 2022-12-06 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0010_remove_table_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
