# Generated by Django 4.1.3 on 2022-12-06 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0011_delete_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
