# Generated by Django 4.1.3 on 2022-12-08 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0013_data_remove_table_data_table_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='data',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.AddField(
            model_name='table',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
