# Generated by Django 4.1.3 on 2022-12-08 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0014_remove_table_data_delete_data_table_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.PositiveSmallIntegerField(default=0, max_length=1)),
                ('data', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.RemoveField(
            model_name='table',
            name='data',
        ),
    ]
