# Generated by Django 4.1.3 on 2022-12-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0015_order_remove_table_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
